name: Auto commit changes

on:
  push:
    branches:
      - main
      - 'release/*'

jobs:
  commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - run: echo -e "\n$(date)" >> README.md

      - name: Push signed commit to staging branch
        uses: planetscale/ghcommit-action@v0.2.18
        with:
          commit_message: "chore: auto commit"
          repo: ${{ github.repository }}
          branch: auto-commit/${{ github.run_id }}
          create_branch: true
          base_branch: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "chore: auto commit README update"
          body: |
            - Triggered by: ${{ github.event_name }}
            - Branch: ${{ github.ref_name }}
          branch: auto-commit/${{ github.run_id }}
          base: ${{ github.ref_name }}
          delete-branch: true
          labels: automated-pr